stages:
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
  - applyYamlConfig:
      path: ./service.yaml
  - applyYamlConfig:
      path: ./ingress.yaml
timeout: 60
notification: {}
